package controle;

import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class frmTela extends javax.swing.JFrame {

    Conexao con_cliente;

    public frmTela() {
        initComponents();
        con_cliente = new Conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from produtos order by id_produto");
        preencherTabela();
        posicionarRegistros();
        produtos.setAutoCreateRowSorter(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. cod 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnUltimoRegistro = new javax.swing.JButton();
        btnPrimeiroRegistroActionPerformed = new javax.swing.JButton();
        txt_pesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        Campodesc = new javax.swing.JTextField();
        Campoval = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Campoquant = new javax.swing.JTextField();
        btnUltimoRegistro2 = new javax.swing.JButton();
        btnAvancarUmRegistro = new javax.swing.JButton();
        btnVoltarUmRegistroActionPerformed = new javax.swing.JButton();
        BtnGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Campopro = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        produtos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Campoforn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setBackground(new java.awt.Color(102, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(86, 0, 148));
        jPanel2.setEnabled(false);

        btnNovo.setBackground(new java.awt.Color(153, 0, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Novo.png"))); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovobtnPrimeiroRegistro(evt);
            }
        });

        btnUltimoRegistro.setBackground(new java.awt.Color(153, 0, 255));
        btnUltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Last.png"))); // NOI18N
        btnUltimoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoRegistroActionPerformed(evt);
            }
        });

        btnPrimeiroRegistroActionPerformed.setBackground(new java.awt.Color(153, 0, 255));
        btnPrimeiroRegistroActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/First.png"))); // NOI18N
        btnPrimeiroRegistroActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroRegistro(evt);
            }
        });

        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id produto :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pesquisar por descrição do produto:");

        BtnAlterar.setBackground(new java.awt.Color(153, 0, 255));
        BtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Alterar.png"))); // NOI18N
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor:");

        btnExcluir.setBackground(new java.awt.Color(153, 0, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Excluir.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        Campodesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampodescActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição:");

        Campoquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoquantActionPerformed(evt);
            }
        });

        btnUltimoRegistro2.setBackground(new java.awt.Color(153, 0, 255));
        btnUltimoRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Sair.png"))); // NOI18N
        btnUltimoRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoRegistro2ActionPerformed(evt);
            }
        });

        btnAvancarUmRegistro.setBackground(new java.awt.Color(153, 0, 255));
        btnAvancarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Go.png"))); // NOI18N
        btnAvancarUmRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarUmRegistroActionPerformed(evt);
            }
        });

        btnVoltarUmRegistroActionPerformed.setBackground(new java.awt.Color(153, 0, 255));
        btnVoltarUmRegistroActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Playback.png"))); // NOI18N
        btnVoltarUmRegistroActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarUmRegistroActionPerformedActionPerformed(evt);
            }
        });

        BtnGravar.setBackground(new java.awt.Color(153, 0, 255));
        BtnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Save.png"))); // NOI18N
        BtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade:");

        Campopro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoproActionPerformed(evt);
            }
        });

        produtos.setBackground(new java.awt.Color(255, 102, 255));
        produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_produto", "Quant", "Descriçao ", "Valor", "Id_forn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtos.setGridColor(new java.awt.Color(0, 0, 0));
        produtos.setSelectionBackground(new java.awt.Color(204, 0, 204));
        produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosMouseClicked(evt);
            }
        });
        produtos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                produtosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(produtos);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id_fornecedor:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setText("Loja de Brinquedos");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cadastro de produtos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btnPrimeiroRegistroActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(btnVoltarUmRegistroActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnAvancarUmRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(btnUltimoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(93, 93, 93)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(BtnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(BtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(115, 115, 115)
                                            .addComponent(btnUltimoRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Campoforn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Campopro, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Campoquant, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Campodesc, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Campoval, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Campopro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Campoquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campodesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Campoval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campoforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnVoltarUmRegistroActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvancarUmRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUltimoRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrimeiroRegistroActionPerformed, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnUltimoRegistro2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarActionPerformed
        // TODO add your handling code here:
        String quant = Campoquant.getText();
        String desc = Campodesc.getText();
        String val = Campoval.getText();
        String forn = Campoforn.getText();
        
        try {
            String insert_sql = "insert into produtos(quantidade, descricao, Valor, id_fornecedor) values ('" + quant + "','" + desc + "','" + val + "','" + forn + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação relaizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from produtos order by id_produto");
            con_cliente.resultset.first();
            mostrar_Dados();
            preencherTabela();

        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "/n Erro na gravação: /n" + errosql,
                "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_BtnGravarActionPerformed

    private void btnNovobtnPrimeiroRegistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovobtnPrimeiroRegistro
        // TODO add your handling code here:
        Campopro.setText("");
        Campoquant.setText("");
        Campodesc.setText("");
        Campoval.setText("");
        Campoforn.setText("");
        Campopro.requestFocus();
    }//GEN-LAST:event_btnNovobtnPrimeiroRegistro

    private void btnUltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoRegistroActionPerformed
        // TODO add your handling code here:
        try {
            con_cliente.resultset.last();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não foi possivel acessar o ultimo registro /n" + erro,
                "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnUltimoRegistroActionPerformed

    private void btnAvancarUmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarUmRegistroActionPerformed
        // TODO add your handling code here:
        try {
            con_cliente.resultset.next();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não foi possivel posicionar no proximo registro /n" + erro,
                "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnAvancarUmRegistroActionPerformed

    private void btnVoltarUmRegistroActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarUmRegistroActionPerformedActionPerformed
        // TODO add your handling code here:
        try {
            con_cliente.resultset.previous();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não foi possivel posicionar no registro anterior /n" + erro,
                "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnVoltarUmRegistroActionPerformedActionPerformed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        // TODO add your handling code here:
        try {
            String pesquisa = "select * from produtos where descricao like'" + txt_pesquisar.getText() + "%'";
            con_cliente.executaSQL(pesquisa);

            if (con_cliente.resultset.first()) {
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(null, "/n não existe dados com este paramêtro", "mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "/n Os dados digitados não foram localizados: " + errosql, "mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void txt_pesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisarKeyPressed

    private void btnPrimeiroRegistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroRegistro
        // TODO add your handling code here:
        try {
            con_cliente.resultset.first();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não foi possivel acessar o primeiro registro /n" + erro,
                "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnPrimeiroRegistro

    private void produtosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produtosKeyReleased
        // TODO add your handling code here:
        int linha_selecionada = produtos.getSelectedRow();
        Campopro.setText(produtos.getValueAt(linha_selecionada, 0).toString());
        Campoquant.setText(produtos.getValueAt(linha_selecionada, 1).toString());
        Campodesc.setText(produtos.getValueAt(linha_selecionada, 2).toString());
        Campoval.setText(produtos.getValueAt(linha_selecionada, 3).toString());
        Campoforn.setText(produtos.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_produtosKeyReleased

    private void produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosMouseClicked
        // TODO add your handling code here:
        int linha_selecionada = produtos.getSelectedRow();
        Campopro.setText(produtos.getValueAt(linha_selecionada, 0).toString());
        Campoquant.setText(produtos.getValueAt(linha_selecionada, 1).toString());
        Campodesc.setText(produtos.getValueAt(linha_selecionada, 2).toString());
        Campoval.setText(produtos.getValueAt(linha_selecionada, 3).toString());
        Campoforn.setText(produtos.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_produtosMouseClicked

    private void btnUltimoRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoRegistro2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnUltimoRegistro2ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String sql = "";

        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja  excluir o registro:", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
            if (resposta == 0) {
                sql = "delete from produtos where id_produto = " + Campopro.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if (excluir == 1) {
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from produtos order by id_produto");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistros();

                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } catch (SQLException excecao) {
            JOptionPane.showMessageDialog(null, "/n Erro na exclusão: " + excecao, "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
        String quant = Campoquant.getText();
        String desc = Campodesc.getText();
        String val = Campoval.getText();
        String forn = Campoforn.getText();
        String sql = "";
        String msg = "";

        try {
            if (Campopro.getText().equals("")) {
                sql = "insert into produtos (quantidade,descricao, Valor, id_fornecedor, ) values (quantidade'" + quant + "',descricao'" + desc +  "',Valor'" + val + "',id_fornecedor'" + forn + "')";
                msg = "Alteração  de registro";
            } else {
                sql = "update produtos set quantidade = '" + quant + "',Valor ='" + val + "', id_fornecedor = '" + forn + "', descricao = '" + desc + "' where id_produto = " + Campopro.getText();
                msg = "Alteração  de registro";
            }

            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "Realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from produtos order by id_produto");
            con_cliente.resultset.first();
            mostrar_Dados();
            preencherTabela();

        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "/n Erro na gravção" + errosql,
                "mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void CampodescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampodescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampodescActionPerformed

    private void CampoproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoproActionPerformed

    private void CampoquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoquantActionPerformed

    /**
     * @param args the command line arguments
     */
    public void preencherTabela() {
        produtos.getColumnModel().getColumn(0).setPreferredWidth(4);
        produtos.getColumnModel().getColumn(1).setPreferredWidth(150);
        produtos.getColumnModel().getColumn(2).setPreferredWidth(11);
        produtos.getColumnModel().getColumn(3).setPreferredWidth(14);
        produtos.getColumnModel().getColumn(4).setPreferredWidth(100);

        DefaultTableModel modelo = (DefaultTableModel) produtos.getModel();
        modelo.setNumRows(0);

        try {
            con_cliente.resultset.beforeFirst();
            while (con_cliente.resultset.next()) {
                modelo.addRow(new Object[]{
                    con_cliente.resultset.getString("id_produto"), con_cliente.resultset.getString("quantidade"),
                    con_cliente.resultset.getString("descricao"), con_cliente.resultset.getString("Valor"),
                    con_cliente.resultset.getString("id_fornecedor")
                }
                );

            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Erro ao listar dados da tabela!!: /n" + erro,
                    "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void posicionarRegistros() {
        try {
            con_cliente.resultset.first();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não foi possivel posicionar no primeiro registro: " + erro,
                    "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    public void mostrar_Dados() {
        try {
            Campopro.setText(con_cliente.resultset.getString("id_produto"));
            Campoquant.setText(con_cliente.resultset.getString("quantidade"));
            Campodesc.setText(con_cliente.resultset.getString("descricao"));
            Campoval.setText(con_cliente.resultset.getString("Valor"));
            Campoforn.setText(con_cliente.resultset.getString("id_fornecedor"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "/n Não localizou dados: " + erro,
                    "mensagem so programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnGravar;
    private javax.swing.JTextField Campodesc;
    private javax.swing.JTextField Campoforn;
    private javax.swing.JTextField Campopro;
    private javax.swing.JTextField Campoquant;
    private javax.swing.JTextField Campoval;
    private javax.swing.JButton btnAvancarUmRegistro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiroRegistroActionPerformed;
    private javax.swing.JButton btnUltimoRegistro;
    private javax.swing.JButton btnUltimoRegistro2;
    private javax.swing.JButton btnVoltarUmRegistroActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable produtos;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
}
